---
- name: File permissions elasticsearch home
  file: path={{ logserver_home }}/elasticsearch-{{elasticsearch_version}} state=directory recurse=yes group={{ elasticsearch_group }} owner={{ elasticsearch_user }}

- name: Create /var/log/elasticsearch
  file: path=/var/log/elasticsearch state=directory recurse=yes mode=a+w group={{ elasticsearch_group }} owner={{ elasticsearch_user }}

- name: Create elasticsearch data dir
  file: path={{ logserver_home }}/elasticsearch-{{ elasticsearch_version }}/data state=directory recurse=yes mode=a+w owner={{ elasticsearch_user }} group={{ elasticsearch_group }}
  
- name: Create elasticsearch scripts dir
  file: path={{ logserver_home }}/elasticsearch-{{ elasticsearch_version }}/scripts state=directory recurse=yes mode=0755 owner={{ elasticsearch_user }} group={{ elasticsearch_group }}
    
  
- name: Create elasticsearch pid dir
  file: path=/var/run/elasticsearch state=directory owner={{ user }} group={{ elasticsearch_group }}
  
- name: Configure Elasticsearch elasticsearch.yml
  sudo: yes
  template:
    src: elasticsearch.yml.j2
    dest: "{{ logserver_home }}/elasticsearch-{{ elasticsearch_version }}/config/{{ elasticsearch_conf }}"
  notify:
    - start elasticsearch
